apiVersion: v1
kind: Service
metadata:
  name: supermario-service
  namespace: staging
  labels:
    tag: argocd-app
    env: staging
spec:
  ports:
  - name: supermario
    protocol: TCP
    port: 8080
  selector:
    tag: argocd-app
