apiVersion: apps/v1
kind: Deployment
metadata:
  name: supermario
  namespace: superbai
spec:
  selector: 
    matchLabels:
      tag: argocd-app
  replicas: 1
  template: 
    metadata:
      labels:
        tag: argocd-app
    spec:
      containers:
      - name: supermario
        image: newdeal123/argocd-app:{Jenkins build number}
        ports:
        - containerPort: 8080 

