apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-develop
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/newdeal123/argoCD-app-config.git
    targetRevision: HEAD
    path: develop
  destination:
    server: https://kubernetes.default.svc
    namespace: develop
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true