apiVersion: apps/v1
kind: Deployment
metadata:
  name: supermario
  namespace: develop
spec:
  selector: 
    matchLabels:
      tag: argocd-app
  replicas: 1
  template: 
    metadata:
      labels:
        tag: argocd-app
        env: devlop
    spec:
      containers:
      - name: supermario
        image: newdeal123/argocd-app:23
        ports:
        - containerPort: 8080 

